### ISSUE TITLE
Weight Cell Correspondeces

### ISSUE THREAD

**Issue by fabianhf** [azaganidis/se_ndt#10]
Hello,

first of all: Thanks for providing this package, great work!

I am currently trying to implement some modifications. In particular, i want to weight the influence of corresponding cells by a linear factor based on some cell properties. From a theoretical standpoint, all derivatives should also be affected linearly.

@azaganidis, i didn't fully understand how you implemented the derivative calculation, could you give me a pointer on where to scale Score, Gradient and Hessian? I suppose changing sh in https://github.com/azaganidis/se_ndt/blob/6d9cdb99992f3422f425088f61fe9749411fb759/src/ndt_matcher_d2d_se.cpp#L277
might be sufficient, but i am not quite sure.

Thanks for your help!

**Comment by azaganidis** [comment]
Hello, 
this will scale the score function, the scaling of the gradient/hessian can be done in https://github.com/azaganidis/se_ndt/blob/6d9cdb99992f3422f425088f61fe9749411fb759/oru_minimal/src/ndt_matcher_d2d.cpp#L439
