### ISSUE TITLE
some errors when I use catkin build.

### ISSUE THREAD

**Issue by kaynezhangqy** [azaganidis/se_ndt#11]
`Errors     << se_ndt:make /home/noname/catkin_ws/logs/se_ndt/build.make.001.log                                                                                
/home/noname/catkin_ws/src/se_ndt/src/se_ndt.cpp: In member function ‘void NDTMatch_SE::slam(pcl::PointCloud<pcl::PointXYZI>::Ptr)’:
/home/noname/catkin_ws/src/se_ndt/src/se_ndt.cpp:240:13: error: invalid controlling predicate
             for(std::vector<int>::iterator it=poseIdxSearch.begin();
             ^~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-dev’
make[2]: *** [CMakeFiles/se_ndt.dir/src/se_ndt.cpp.o] Error 1
make[1]: *** [CMakeFiles/se_ndt.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by azaganidis** [comment]
Hello, Thank you for the interest and trying out this library. 
The problem must be with the OpenMP version (see [here](https://forum.openmp.org/viewtopic.php?t=746)). Which one are you using?
A workaround might be to modify in  [L237](https://github.com/azaganidis/se_ndt/blob/6d9cdb99992f3422f425088f61fe9749411fb759/src/se_ndt.cpp#L237):            
`#pragma omp parallel num_threads(N_THREADS)`
 `{`
`     #pragma omp for`
`     for(std::vector<int>::iterator it=poseIdxSearch.begin();it!=poseIdxSearch.end();++it)`
can be replaced with 
`std::vector<int>::iterator begin_tmp = poseIdxSearch.begin();`
`std::vector<int>::iterator end_tmp = poseIdxSearch.end();`
`#pragma omp parallel num_threads(N_THREADS)`
` {`
`     #pragma omp for`
`     for(std::vector<int>::iterator it=begin_tmp;it<=end_tmp;++it)`
Please let me know if that works.

**Comment by kaynezhangqy** [comment]
@azaganidis 

Thank you for your reply. 
The version of openMp I am using is 201511.
 Following your suggestion, I modified the code and it works. In fact,I just modified it like this:
`for(std::vector<int>::iterator it=begin_tmp;it<end_tmp;++it)`
Thank you again!

**Comment by azaganidis** [comment]
Good to know, thanks!
