### ISSUE TITLE
About pointnet.pb

### ISSUE THREAD

**Issue by zhuyachen** [azaganidis/se_ndt#4]
Hello  @azaganidis 
Thanks for your great work !
I'm learning your open source code of se_ndt， could you please give me your trained model ?   My e-mail is 940901516@qq.com.
I promise not to be used for commercial purposes, but for learning.Thanks very much.

**Comment by zhuyachen** [comment]
Oh,I just found the file...but could you tell me the version of  your tensorflow ?because I have to install the corresponding version to load the .pb file.

**Comment by azaganidis** [comment]
Hello @zhuyachen , all experiments where done using tensorflow 1.10

**Comment by zhuyachen** [comment]
Thanks for your reply.I try to run the code with tensorflow 1.10.0.However I still can't load the model successfully.The session may not be created properly, so as soon as I run the session, it will cause core dumped.The details is here:
`Not found: Op type not registered 'FarthestPointSample' in binary running on chen. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.     

Invalid argument: Session was not created with a graph before Run()!     

Segmentation Fault(core dumped)
`
I just used"**pip install tensorflow-gpu==1.10**" in  the Anaconda  python 3.6 environment to install the training environment, then download the source code of both TF  1.10.1 and TF 1.10.0 (and there are other 1.10 versions such as 1.10.0-rc1 on this website [https://github.com/tensorflow/tensorflow/releases?after=v1.11.0](https://github.com/tensorflow/tensorflow/releases?after=v1.11.0)  ).After compiled by bazel 0.15.0,I used the libtensorflow_cc.so and libtensorflow_framework.so to  link the deploy.cpp.o.But both TF C++ API encounter the bug.It seems to be the problems of the TF version,but I can't fix it... do you have any idea about it? @azaganidis

**Comment by azaganidis** [comment]
Are you building deploy.cpp using cmake with the pointnet2/deploy/CMakeLists.txt ?
The file is linked with this operator at line 86. Can you check that it is built correctly?

**Comment by zhuyachen** [comment]
Yes,I just use that CMakelists.txt file but I modified some of it to adapt to my environment .
I used the commend  **nm -C libtf_ops.so | grep FarthestPointSample** to check the function status,the result is:

> 00000000000108e0 W FarthestPointSampleGpuOp::Compute(tensorflow::OpKernelContext*)
0000000000010400 W FarthestPointSampleGpuOp::~FarthestPointSampleGpuOp()
00000000000103e0 W FarthestPointSampleGpuOp::~FarthestPointSampleGpuOp()
00000000000103e0 W FarthestPointSampleGpuOp::~FarthestPointSampleGpuOp()
000000000027eb80 V typeinfo for FarthestPointSampleGpuOp
0000000000068510 V typeinfo name for FarthestPointSampleGpuOp
000000000027ec00 V vtable for FarthestPointSampleGpuOp

I also check the others such as ProbSample etc. And all the result were just like to the up ones. So Is it right?
I also have another question that if you were use the same TF version when you trained your model and then used it in c++ ? And the one for python was installed by pip and the other one for c++ was installed by compiling source code of TF?

**Comment by ahandsomeperson** [comment]
Hi @zhuyachen  I met the same problem as you. The details is here:

Not found: Op type not registered 'FarthestPointSample' in binary running on lhl-Lenovo-Legion-Y7000P-1060. Make sure the Op and Kernel are registered in the binary running in this process

My tensorflow version is 1.8. Have you solved this problem ?

**Comment by mohammadJalali91** [comment]
Hello
Have you reached the "pointnet.pb" file?
I really need this file, is it possible to give me this file?
I promise it will not be used for commercial purposes, but for learning.
thank you
