### ISSUE TITLE
Some `undefined reference` errors

### ISSUE THREAD

**Issue by bin70** [azaganidis/se_ndt#5]
Hello, thanks so much for your great work and sharing! I'm learning about se_ndt through the source code, but some errors arise when I try to compile the source code:
```
deploy.cpp:(.text._ZN8PointnetC2ERN3ros10NodeHandleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN8PointnetC5ERN3ros10NodeHandleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x43a): undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
deploy.cpp:(.text._ZN8PointnetC2ERN3ros10NodeHandleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN8PointnetC5ERN3ros10NodeHandleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x4ad): undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::MessageLite*)'
deploy.cpp:(.text._ZN8PointnetC2ERN3ros10NodeHandleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN8PointnetC5ERN3ros10NodeHandleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x516): undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
deploy.cpp:(.text._ZN8PointnetC2ERN3ros10NodeHandleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN8PointnetC5ERN3ros10NodeHandleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x5b7): undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const'
```
Then I follow the advice on the web and set the compiler flag as
`-D_GLIBCXX_USE_CXX11_ABI=0`. Although this approach solved the previous error, there have been some new errors:
```
deploy.cpp:(.text._ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE[_ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE]+0x535): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
deploy.cpp:(.text._ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE[_ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE]+0x5b5): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
deploy.cpp:(.text._ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE[_ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE]+0x665): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
deploy.cpp:(.text._ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE[_ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE]+0x70d): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
deploy.cpp:(.text._ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE[_ZNK3ros9Publisher7publishIN3pcl10PointCloudINS2_9PointXYZIEEEEEvRKN5boost10shared_ptrIT_EE]+0x7d5): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
...
deploy.cpp:(.text._ZN5boost15program_options25basic_command_line_parserIcEC2EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC5EiPKPKc]+0x158): undefined reference to `boost::program_options::to_internal(std::string const&)'
deploy.cpp:(.text._ZN5boost15program_options25basic_command_line_parserIcEC2EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC5EiPKPKc]+0x1e0): undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
...
deploy.cpp:(.text.startup+0x1dd): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
deploy.cpp:(.text.startup+0x516): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
deploy.cpp:(.text.startup+0x587): undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
```
I don't know how to go further to successfully compile the source code. Could you please give me some help? And my compilation environment is:
- Ubuntu 16.04
- GCC 6.5.0
- PCL 1.8.1
- ROS Kinetic
- Tensorflow 1.10.0
 
Any help would be appreciated!

**Comment by azaganidis** [comment]
Hello, are you building using cmake and  pointnet2/deploy/CMakeLists.txt ? 
Can you check that the variables 
${ROS_REQUIRED_LIBS}
${Boost_LIBRARIES}
are not empty?
I am building with gcc 7.3.0, but I think that shouldn't affect.

**Comment by bin70** [comment]
Thanks for the reply!

Yes, I use the `pointnet2/deploy/CMakeLists.txt` but make a little modification to adapt to my environment. I use `message(STATUS "")` to print the values of `${ROS_REQUIRED_LIBS}, ${Boost_LIBRARIES}` and get
```
ROS_REQUIRED_LIBS = /opt/ros/kinetic/lib/libroscpp.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_signals.so;/opt/ros/kinetic/lib/librosconsole.so;/opt/ros/kinetic/lib/librosconsole_log4cxx.so;/opt/ros/kinetic/lib/librosconsole_backend_interface.so;/usr/lib/x86_64-linux-gnu/liblog4cxx.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/opt/ros/kinetic/lib/libroscpp_serialization.so;/opt/ros/kinetic/lib/libxmlrpcpp.so;/opt/ros/kinetic/lib/librostime.so;/opt/ros/kinetic/lib/libcpp_common.so; ...
Boost_LIBRARIES = /home/elvin/boost_1_58_0/lib/libboost_system.so;/home/elvin/boost_1_58_0/lib/libboost_filesystem.so;/home/elvin/boost_1_58_0/lib/libboost_thread.so;/home/elvin/boost_1_58_0/lib/libboost_date_time.so;/home/elvin/boost_1_58_0/lib/libboost_iostreams.so;/home/elvin/boost_1_58_0/lib/libboost_chrono.so;/home/elvin/boost_1_58_0/lib/libboost_atomic.so;/home/elvin/boost_1_58_0/lib/libboost_regex.so
```
which shows the two variables are not empty. 

GCC 7.3.0 also have been tried, but cmake was aborted by an error:
```
/usr/local/cuda-9.0/bin/..//include/crt/host_config.h:119:2: error: #error
  -- unsupported GNU version! gcc versions later than 6 are not supported!
```
So I guess it may be attributed to the unsuitable version of dependency libraries I installed (like CUDA 9.0 or even Ubuntu 16.04). Could you give me more detailed information about your environment? Thanks a lot!

**Comment by azaganidis** [comment]
My environment is:
* gcc 7.3.0
* cuda 9.2.88
* eigen 3.3.7
* boost 1.65.0
* pcl-1.8
* catkin 0.7.14
* Python 2.7.15
* ros kinetic

**Comment by asmand001** [comment]
Who can help me solve this problem?   Thanks
CMakeFiles/talker.dir/src/talker.cpp.o：在函数‘main’中：
talker.cpp:(.text+0x70)：对‘ros::init(int&, char**, std::string const&, unsigned int)’未定义的引用
talker.cpp:(.text+0xcc)：对‘ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)’未定义的引用
talker.cpp:(.text+0x29a)：对‘ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)’未定义的引用
CMakeFiles/talker.dir/src/talker.cpp.o：在函数‘void ros::Publisher::publish<std_msgs::String_<std::allocator<void> > >(std_msgs::String_<std::allocator<void> > const&) const’中：
talker.cpp:(.text._ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_]+0xa0)：对‘ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)’未定义的引用
talker.cpp:(.text._ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_]+0x1a3)：对‘ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)’未定义的引用
talker.cpp:(.text._ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_]+0x29e)：对‘ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)’未定义的引用
talker.cpp:(.text._ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_]+0x3c1)：对‘ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)’未定义的引用
CMakeFiles/talker.dir/src/talker.cpp.o:talker.cpp:(.text._ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN8std_msgs7String_ISaIvEEEEEvRKT_]+0x4c4): 跟着更多未定义的参考到 ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)
collect2: error: ld returned 1 exit status
learning_communication/CMakeFiles/talker.dir/build.make:113: recipe for target '/home/asmand/catkin_ws/devel/lib/learning_communication/talker' failed
make[2]: *** [/home/asmand/catkin_ws/devel/lib/learning_communication/talker] Error 1
CMakeFiles/Makefile2:818: recipe for target 'learning_communication/CMakeFiles/talker.dir/all' failed
make[1]: *** [learning_communication/CMakeFiles/talker.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
CMakeFiles/listener.dir/src/listener.cpp.o：在函数‘chatterCallback(boost::shared_ptr<std_msgs::String_<std::allocator<void> > const> const&)’中：
listener.cpp:(.text+0x78)：对‘ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)’未定义的引用
CMakeFiles/listener.dir/src/listener.cpp.o：在函数‘main’中：
listener.cpp:(.text+0x1dc)：对‘ros::init(int&, char**, std::string const&, unsigned int)’未定义的引用
listener.cpp:(.text+0x238)：对‘ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)’未定义的引用
CMakeFiles/listener.dir/src/listener.cpp.o：在函数‘ros::SubscriptionCallbackHelperT<boost::shared_ptr<std_msgs::String_<std::allocator<void> > const> const&, void>::deserialize(ros::SubscriptionCallbackHelperDeserializeParams const&)’中：
listener.cpp:(.text._ZN3ros27SubscriptionCallbackHelperTIRKN5boost10shared_ptrIKN8std_msgs7String_ISaIvEEEEEvE11deserializeERKNS_43SubscriptionCallbackHelperDeserializeParamsE[_ZN3ros27SubscriptionCallbackHelperTIRKN5boost10shared_ptrIKN8std_msgs7String_ISaIvEEEEEvE11deserializeERKNS_43SubscriptionCallbackHelperDeserializeParamsE]+0xba)：对‘ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)’未定义的引用
collect2: error: ld returned 1 exit status
learning_communication/CMakeFiles/listener.dir/build.make:113: recipe for target '/home/asmand/catkin_ws/devel/lib/learning_communication/listener' failed
make[2]: *** [/home/asmand/catkin_ws/devel/lib/learning_communication/listener] Error 1
CMakeFiles/Makefile2:557: recipe for target 'learning_communication/CMakeFiles/listener.dir/all' failed
make[1]: *** [learning_communication/CMakeFiles/listener.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
